server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-2t27j0ndasw4an67.us.auth0.com/

  datasource:
    url: jdbc:postgresql://localhost:5432/blog_site
    username: postgres
    password: 1823
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
